export enum modProtocolName {
    SceneProtocol = "scene-protocol",
    MMDCharacterProtocol = "mmd-character-protocol",
    CareerProtocol = "career-protocol",
    CareerFeatureProtocol = "career-feature-protocol",
    SettingProtocol = "setting-protocol",
    EnemyEliteGiantessProtocol = "enemy-elite-giantess-protocol",
    EnemyEliteGiantessShareProtocol = "enemy-elite-giantess-share-protocol",
    ParticleProtocol = "particle-protocol",
    ParticleShareProtocol = "particle-share-protocol",
    BuffProtocol = "buff-protocol",
    UpgradeProtocol = "upgrade-protocol",
    EventGameProtocol = "event-game-protocol",
    BehaviourProtocol = "behaviour-protocol",
    FSMProtocol = "fsm-protocol",
    PropBulletProtocol = "prop-bullet-protocol",
    PropOtherProtocol = "prop-other-protocol",
    LevelGiantessProtocol = "level-giantess-protocol",
    WeaponProtocol = "weapon-protocol",
    SkillLittleManProtocol = "skill-little-man-protocol",
    SkillGiantessProtocol = "skill-giantess-protocol",
    InteractionProtocol = "interaction-protocol",
}

export type blockName = string